### ISSUE TITLE
The enlarged result is different from waifu2x-caffe.

### ISSUE THREAD

**Issue by f11894** [nihui/waifu2x-ncnn-vulkan#4] opened 2019-04-07 11:06 UTC
Ryzen 2400G
[0 AMD Radeon(TM) RX Vega 11 Graphics]  queueC=1  queueT=2  memU=2  memDL=0  memHV=1
[0 AMD Radeon(TM) RX Vega 11 Graphics]  fp16s=1  fp16a=1  int8s=1  int8a=1

input file
![test](https://user-images.githubusercontent.com/16046279/55682508-a79f7d00-596f-11e9-8120-203d3b1db593.png)

waifu2x-ncnn-vulkan ver 20190407
```
waifu2x.exe "%~1" "%~dpn1-ncnn-vulkan-2x.png" -1 2
waifu2x.exe "%~dpn1-ncnn-vulkan-2x.png" "%~dpn1-ncnn-vulkan-4x.png" -1 2
```
![test-ncnn-vulkan-4x](https://user-images.githubusercontent.com/16046279/55682540-fd742500-596f-11e9-8a10-9a7ab76034ec.png)

waifu2x-caffe ver 1.2.0.2
```
waifu2x-caffe-cui.exe -t 0 -b 1 -c 128 -p cpu --model_dir ./models/cunet -s 2 -m scale -i "%~1" -o "%~dpn1-caffe-2x.png"
waifu2x-caffe-cui.exe -t 0 -b 1 -c 128 -p cpu --model_dir ./models/cunet -s 2 -m scale -i "%~dpn1-caffe-2x.png" -o "%~dpn1-caffe-4x.png"
```
![test-caffe-4x](https://user-images.githubusercontent.com/16046279/55682545-17156c80-5970-11e9-8723-1d6688cf4a63.png)

**Comment by Dearmw** [comment] 2019-04-07 11:22
Input
waifu2x 1.jpg 2.jpg 2 2
![1](https://user-images.githubusercontent.com/14261260/55682764-481d7f00-5927-11e9-97a6-0df41c755050.jpg)
Output
![2](https://user-images.githubusercontent.com/14261260/55682770-579cc800-5927-11e9-8ccc-6ae4a959d23d.jpg)

**Comment by Dearmw** [comment] 2019-04-07 11:25
Input
![1](https://user-images.githubusercontent.com/14261260/55682793-9894dc80-5927-11e9-8266-bcd122451c2f.jpg)


Running code  waifu2x 1.jpg 2.jpg 2 2
[0 Radeon RX Vega]  queueC=1  queueT=2  memU=2  memDL=0  memHV=1
[0 Radeon RX Vega]  fp16s=1  fp16a=1  int8s=1  int8a=1


Output
![2](https://user-images.githubusercontent.com/14261260/55682802-acd8d980-5927-11e9-9cd8-038053759fcb.jpg)

**Comment by f11894** [comment] 2019-04-07 11:34
In addition, Benchmark score seems to be worse than waifu2x-caffe.
Average score of 55 images.

waifu2x-caffe CUnet
37.619dB

waifu2x-ncnn-vulkan CUnet
34.469dB

This is the bat file I used for benchmarking.
https://github.com/f11894/SR_benchmark

I use Google Translate because I am not good at English.

**Comment by nihui** [comment] 2019-04-07 12:36
> 
> 
> Input
> ![1](https://user-images.githubusercontent.com/14261260/55682793-9894dc80-5927-11e9-8266-bcd122451c2f.jpg)
> 
> Running code waifu2x 1.jpg 2.jpg 2 2
> [0 Radeon RX Vega] queueC=1 queueT=2 memU=2 memDL=0 memHV=1
> [0 Radeon RX Vega] fp16s=1 fp16a=1 int8s=1 int8a=1
> 
> Output
> ![2](https://user-images.githubusercontent.com/14261260/55682802-acd8d980-5927-11e9-9cd8-038053759fcb.jpg)

the incorrect output caused by fp16 arithmetic on gtx20/rtx20/vega issue is confirmed. A workaround will be applied for these gpu soon...

**Comment by nihui** [comment] 2019-04-07 12:44
thanks for your report
will investigate ...

**Comment by Dearmw** [comment] 2019-04-07 13:26
> 感谢您的报告
> 将进行调查......
Are you from Shanghai?

**Comment by nihui** [comment] 2019-04-07 13:58
deconvolution operator produce wrong result on fp16 storage/arithmetic mode.
I will fix it soon ...

**Comment by nihui** [comment] 2019-04-07 14:05
the underlying ncnn library get fixed in https://github.com/Tencent/ncnn/commit/9643916281dcd35cf2ffc2b7e44cf61fe6561d7b
new binary will be rebuild and uploaded about an hour later, stay tuned ...

**Comment by nihui** [comment] 2019-04-07 15:08
20190407 package updated, please try the new binary

**Comment by f11894** [comment] 2019-04-07 22:04
There is no change in the output result using the new binary.
MD5 is also consistent with the previous.

**Comment by nihui** [comment] 2019-04-08 02:55
> 
> 
> There is no change in the output result using the new binary.
> MD5 is also consistent with the previous.

hi, I just tried the new binary with your original image on AMD r9-m290x machine and my Intel UHD 620 laptop, the output image looks the same with caffe one.

waifu2x.exe
SHA1: 6892F871041F4DAE1BF74FF9692547317A99DFBD

**Comment by f11894** [comment] 2019-04-08 04:40
I'm sorry I didn't have enough words.
MD5 is from the output PNG image, not the executable file.

When I converted the sample described in README.md, I noticed that I could not get the same result as you.
Apparently there are things that do not work well depending on the environment.
![image](https://user-images.githubusercontent.com/16046279/55698928-41643a00-5a03-11e9-98c4-2ccf9f550ad7.png)

**Comment by nihui** [comment] 2019-04-08 05:33
> I'm sorry I didn't have enough words.
> MD5 is from the output PNG image, not the executable file.
> 
> When I converted the sample described in README.md, I noticed that I could not get the same result as you.
> Apparently there are things that do not work well depending on the environment.
> ![image](https://user-images.githubusercontent.com/16046279/55698928-41643a00-5a03-11e9-98c4-2ccf9f550ad7.png)

another issue which affects modern gpu with fp16a capability is confirmed.
because of lack of these specific devices, I may try to figure it out with some workarounds.

**Comment by nihui** [comment] 2019-04-08 14:20
new binary 20190408 has been uploaded with a workaround for gtx20 and vega series.
please try this new version and see if this issue still exists.

**Comment by kalcohol** [comment] 2019-04-08 16:44
@nihui @f11894 @Dearmw 
i tested version 20190408, it seems this issue was fixed @RTX2060 and RTX2080.

**Comment by f11894** [comment] 2019-04-08 20:56
Even in my environment, I confirmed that this problem was solved.
The output result is equivalent to waifu2x-caffe.

**Comment by f11894** [comment] 2019-04-08 21:44
In the case of visual inspection, I do not feel much difference, but there seems to be a little difference in the score of Benchmark.

waifu2x-caffe CUnet
37.619dB

waifu2x-ncnn-vulkan(20190408) CUnet
36.942dB

**Comment by f11894** [comment] 2019-04-14 00:12
https://i.imgur.com/SFs1Ws8.gif

If you look closely and compare it, the contrast of the image seems different.
Will the problem be corrected if the bug related to fp16a is fixed?

よく見比べてみると画像のコントラストが異なるようです。
fp16aに関する不具合が修正されるとこの問題は修正されますか？

**Comment by nihui** [comment] 2019-04-14 00:47
> 
> 
> https://i.imgur.com/SFs1Ws8.gif
> 
> If you look closely and compare it, the contrast of the image seems different.
> Will the issue be solved if the bug related to fp16a is fixed?
> 
> よく見比べてみると画像のコントラストが異なるようです。
> fp16aに関する不具合が修正されるとこの問題は解決しますか？

yeah, I found the little difference too.
It is not because of fp16s or fp16a, but because of postprocess.
waifu2x-caffe add a small eps value to all pixels during postprocess, while waifu2x-ncnn-vulkan do not.
I may port this behavior to let the result pixel-wise identity to the caffe one.

**Comment by nihui** [comment] 2019-04-14 05:31
20190414 package updated, please try the new binary
the result is still not pixel-wise identity to the caffe output due to loss-of-precision during floating point arithmetic and fp16 storage conversion
but it is close enough I think  ^^:)

**Comment by f11894** [comment] 2019-04-14 07:55
Yes, ver 20190414 is almost the same as waif2x-caffe.
You will not notice the difference unless you compare them fairly carefully.

はい、ver 20190414ではwaif2x-caffeと殆ど変わらなくなりました。
かなり注意深く比較しない限り違いに気づくことはありません。

||PSNR(RGB)|SSIM(RGB)|total time(s)|
|---|---|---|---|
|waifu2x-caffe|37.619|0.987|20.250|
|waifu2x-ncnn-vulkan(20190407)|34.469|0.975|8.557|
|waifu2x-ncnn-vulkan(20190408)|36.942|0.986|8.664|
|waifu2x-ncnn-vulkan(20190414)|37.334|0.986|3.641|

**Closed** 2019-04-17 00:12 UTC
Labels: bug

**Comment by fleafed** [comment] 2021-01-05 22:09
Maybe it would upscale better if you weren't a pedophile
