### ISSUE TITLE
.png.png file extension name issue

### ISSUE THREAD

**Issue by lextra2** [nihui/waifu2x-ncnn-vulkan#30] opened 2019-07-20 20:31 UTC
When using batch processing, and when exposing the file extension in the windows file explorer, the images in the output folder result in a .png.png file name.
example: 
input: image01.png
output: image01.png.png

**Comment by nihui** [comment] 2019-07-21 01:20
duplicate of https://github.com/nihui/waifu2x-ncnn-vulkan/issues/27

**Closed by nihui** 2019-07-21 01:20 UTC
