### ISSUE TITLE
[Request] Batch-Upscaling Request

### ISSUE THREAD

**Issue by aka-katto** [nihui/waifu2x-ncnn-vulkan#21] opened 2019-07-01 08:37 UTC
Currently if a user wants to upscale multiple photos using waifu2x-ncnn-vulkan, it works as follows:

`for every image in folder`
` | load vulkan runtime initialization`
` | load image`
` | upscale image`
` | save image`

In a previous post you commented:

> A really large portion of the consumed time is for the vulkan runtime initialization

If we can instead do

` load vulkan runtime initialization`
`for every image in folder`
` | load image`
` | upscale image`
` | save image`

We could save a lot of computational time. It could be used in dandere2x

https://github.com/aka-katto/dandere2x

and k4yt3x's video2x

https://github.com/k4yt3x/video2x

**Comment by nagadomi** [comment] 2019-07-01 10:18
Moreover, load/save image(Disk IO, PNG decode/encode) are can be parallelized with upscale image(GPU task).

**Comment by sat3ll** [comment] 2019-07-01 15:10
Duplicate of point 2, #20

**Comment by nihui** [comment] 2019-07-12 15:34
https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20190712
just posted a new waifu2x-ncnn-vulkan release, please let me know if you encounter problems

**Closed by nihui** 2019-07-12 15:34 UTC
Labels: enhancement
