### ISSUE TITLE
Segmentation Fault on M1 Macbook

### ISSUE THREAD

**Issue by aozaki-kuro** [nihui/waifu2x-ncnn-vulkan#160] opened 2021-07-25 01:56 UTC
I'm using MacBook Air (M1, 2020) and this is the problem I have found:

I downloaded the newest version ([Release 20210521](https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20210521)) and put the folder in `/Users/aozaki/Documents/waifu2x-ncnn-vulkan`.
I also added `$PATH` in `.zshrc`.

But when I use `/Users/aozaki/Documents/waifu2x-ncnn-vulkan/waifu2x-ncnn-vulkan -i "pic1.jpg" -o "pic2.jpg"` it returns messages like `[1]    65343 segmentation fault /Users/aozaki/Documents/waifu2x-ncnn-vulkan/waifu2x-ncnn-vulkan -i -o`

I have to `cd /Users/aozaki/Documents/waifu2x-ncnn-vulkan/` then use the command `waifu2x-ncnn-vulkan -i "pic1.jpg" -o "pic2.jpg"` and it works.

Things are all good on Windows 10, add `$PATH` and it works all good.

How should I fix the problem? Thanks!

**Comment by Nova-Aurora** [comment] 2021-09-02 22:38
This may be unrelated, but did you rename the executable file in the waifu2x-ncnn-vulkan folder? Because the default name for both the executable and the command in path is waifu2x-ncnn-vulkan, not waifu2x, which can be used by some other waifu2x programs.

**Comment by aozaki-kuro** [comment] 2021-09-03 00:25
> This may be unrelated, but did you rename the executable file in the waifu2x-ncnn-vulkan folder? Because the default name for both the executable and the command in path is waifu2x-ncnn-vulkan, not waifu2x, which can be used by some other waifu2x programs.

I have tried this in the condition both renamed and unrenamed. They all returned `24349 segmentation fault`.

**Comment by diamondsw** [comment] 2021-10-12 14:27
I've run into this as well; many of the waifu variants assume their working directory is where the binary is located, and segfault when you attempt to execute them from elsewhere. For now I've just written a wrapper script that cd's before running. Ugly hack, but works.

**Comment by thallium** [comment] 2021-11-13 17:29
> I've run into this as well; many of the waifu variants assume their working directory is where the binary is located, and segfault when you attempt to execute them from elsewhere. For now I've just written a wrapper script that cd's before running. Ugly hack, but works.

can you elaborate on the cause?

**Comment by nihui** [comment] 2022-04-19 10:53
fixed in https://github.com/nihui/waifu2x-ncnn-vulkan/commit/7ab564a955c23bcfbdabfe093a1791f5a761cb32

**Closed by nihui** 2022-04-19 10:53 UTC
