### ISSUE TITLE
WebP file support

### ISSUE THREAD

**Issue by StarSparkleNova** [nihui/waifu2x-ncnn-vulkan#66] opened 2020-04-15 01:25 UTC
Could we some Webp file support as input? Cheers

**Comment by Nova-Aurora** [comment] 2020-05-21 18:31
It would be nice, however it could also create a large number of dependencies and make building more complicated.

**Comment by Nova-Aurora** [comment] 2020-05-21 18:40
waifu2x-ncnn-vulkan uses stb for image coding on linux and macos, which only supports JPG, PNG, TGA, BMP, PSD, GIF, HDR, PIC for decoding and PNG, TGA, BMP for coding. So one would need to add another image decoder for webp support.

**Comment by Nova-Aurora** [comment] 2020-05-21 18:43
Currently my workaround is to use imagemagick to convert to .png losslessly, then run w2x, then use either libwebp or [Squoosh](https://squoosh.app/) to convert back to webp.

**Comment by Nova-Aurora** [comment] 2020-05-21 19:24
Also on the "nice to have" list:
 HEIC (Iphone output)
AVIF
JPG2000
JPEG-XL

**Comment by nihui** [comment] 2020-05-22 15:19
duplicate of https://github.com/nihui/waifu2x-ncnn-vulkan/issues/15

**Closed by nihui** 2020-05-22 15:19 UTC
